CREATE OR REPLACE PROCEDURE STUDENT_PERF
(
V_IN_STUDENTGPA IN NUMBER
)
AS
TYPE STUD_REC IS RECORD
    (STUDENT_ID NUMBER,
    GPA NUMBER);
TYPE STUD_REC_TAB IS TABLE OF STUD_REC;
V_STUDENTTAB STUD_REC_TAB := STUD_REC_TAB();
V_RESULTCURSOR SYS_REFCURSOR;
BEGIN
OPEN V_RESULTCURSOR FOR
     SELECT STUDENT_ID, GPA 
       FROM STUDENT 
      WHERE GPA < V_IN_STUDENTGPA;
LOOP
  FETCH V_RESULTCURSOR
   BULK COLLECT INTO V_STUDENTTAB;
   EXIT WHEN V_RESULTCURSOR%NOTFOUND;
END LOOP;
CLOSE V_RESULTCURSOR;
FOR I IN V_STUDENTTAB.FIRST .. V_STUDENTTAB.LAST LOOP
  DBMS_OUTPUT.PUT_LINE('Student id ' || V_STUDENTTAB(I).STUDENT_ID || ' Student gpa ' || V_STUDENTTAB(I).GPA);
END LOOP;
END;